#pragma once

#define SEAD_VERSION_BOTW 1
#define SEAD_VERSION_SMO 2
#define SEAD_VERSION_SPL3 3
#define SEAD_VERSION_TOTK 4
#define SEAD_VERSION_SMBW 5
#define SEAD_VERSION_CUSTOM 0

#ifndef SEAD_VERSION
#define SEAD_VERSION SEAD_VERSION_BOTW
#endif

/// sead version features:
///
/// SEAD_SAFESTRING_NONVIRTUAL:
///     Devirtualizes SafeString, removing its virtual table.
/// SEAD_RESOURCEMGR_TRYCREATE_NO_FACTORY_NAME:
///     Removes factory_name argument from ResourceMgr::tryCreate
/// SEAD_CRITICALSECTION_PURE:
///     Removes IDisposer from CriticalSection
/// SEAD_THREADMGR_MOVED_SINGLETON_DISPOSER:
///     Moves ThreadMgr's singleton disposer to the end of the class
/// SEAD_HEAP_FREEANDGETALLOCATABLESIZE_VIRTUAL:
///     Adds freeAndGetAllocatableSize virtual to Heap
/// SEAD_RTTI_CHECKDERIVEDRUNTIMETYPEINFO_RETURNS_INSTANCE:
///     Makes checkDerivedRuntimeTypeInfo return the object instance instead of a boolean
/// SEAD_THREAD_GETFIBER:
///     Adds virtual getFiber to Thread (and removes getStackCheckStartAddress_)
/// SEAD_DELEGATE_ISNODUMMY:
///     Add isNoDummy() and operator bool() to Delegates

#if SEAD_VERSION == SEAD_VERSION_BOTW
#define SEAD_SAFESTRING_NONVIRTUAL 0
#define SEAD_RESOURCEMGR_TRYCREATE_NO_FACTORY_NAME 0
#define SEAD_CRITICALSECTION_PURE 0
#define SEAD_THREADMGR_MOVED_SINGLETON_DISPOSER 0
#define SEAD_HEAP_FREEANDGETALLOCATABLESIZE_VIRTUAL 0
#define SEAD_RTTI_CHECKDERIVEDRUNTIMETYPEINFO_RETURNS_INSTANCE 0
#define SEAD_THREAD_GETFIBER 0
#define SEAD_DELEGATE_ISNODUMMY 1
#elif SEAD_VERSION == SEAD_VERSION_SMO
#define SEAD_SAFESTRING_NONVIRTUAL 0
#define SEAD_RESOURCEMGR_TRYCREATE_NO_FACTORY_NAME 0
#define SEAD_CRITICALSECTION_PURE 0
#define SEAD_THREADMGR_MOVED_SINGLETON_DISPOSER 0
#define SEAD_HEAP_FREEANDGETALLOCATABLESIZE_VIRTUAL 0
#define SEAD_RTTI_CHECKDERIVEDRUNTIMETYPEINFO_RETURNS_INSTANCE 0
#define SEAD_THREAD_GETFIBER 0
#define SEAD_DELEGATE_ISNODUMMY 0
#elif SEAD_VERSION == SEAD_VERSION_SPL3 or SEAD_VERSION == SEAD_VERSION_TOTK or                    \
    SEAD_VERSION == SEAD_VERSION_SMBW
#define SEAD_SAFESTRING_NONVIRTUAL 1
#define SEAD_RESOURCEMGR_TRYCREATE_NO_FACTORY_NAME 1
#define SEAD_CRITICALSECTION_PURE 1
#define SEAD_THREADMGR_MOVED_SINGLETON_DISPOSER 1
#define SEAD_HEAP_FREEANDGETALLOCATABLESIZE_VIRTUAL 1
#define SEAD_RTTI_CHECKDERIVEDRUNTIMETYPEINFO_RETURNS_INSTANCE 1
#define SEAD_THREAD_GETFIBER 1
#define SEAD_DELEGATE_REMOVE_ISNODUMMY 0
#endif

/// feature-specific macros

#if SEAD_SAFESTRING_NONVIRTUAL
#define SEAD_SAFESTRING_VIRTUAL_TOKEN
#define SEAD_SAFESTRING_OVERRIDE_TOKEN
#else
#define SEAD_SAFESTRING_VIRTUAL_TOKEN virtual
#define SEAD_SAFESTRING_OVERRIDE_TOKEN override
#endif

#if SEAD_CRITICALSECTION_PURE
#define SEAD_CRITIALSECTION_OVERRIDE_TOKEN
#else
#define SEAD_CRITIALSECTION_OVERRIDE_TOKEN override
#endif
